services:
  Arch-Function-7B:
    image: vllm/vllm-openai:latest
    entrypoint: [
      "vllm", "serve", "katanemo/Arch-Function-7B",
      "--enable-prefix-caching", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "131072",
      "--enable-auto-tool-choice", "--tool-call-parser", "hermes",
      "--trust-remote-code"
    ]
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HUGGINGFACE_TOKEN:?error}
    volumes:
      - type: bind
        source: ${HF_HOME:?error}
        target: /root/.cache/huggingface
      - type: bind
        source: ./node/inference/configs
        target: /usr/app # configs like chat templates, vllm configs, tool parsers
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ "gpu" ]
              device_ids: [ "0" ]
  
networks:
  naptha-network:
    external: true