services:
  microsoft/phi-4:
    image: vllm/vllm-openai:latest
    entrypoint: [
      "vllm", "serve", "microsoft/phi-4",
      "--enable-prefix-caching", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "16384",
      "--trust-remote-code"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - type: bind
        source: ${HF_HOME:?error}
        target: /root/.cache/huggingface
      - type: bind
        source: ./node/inference/configs
        target: /usr/app # configs like chat templates, vllm configs, tool parsers
    ipc: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ "gpu" ]
              device_ids: [ "${GPU_ID_phi_4:?error}" ]
    networks:
      - naptha-network

networks:
  naptha-network:
    external: true