model_list:

  # vllm-0 hermes
  - model_name: NousResearch/Hermes-3-Llama-3.1-8B
    litellm_params:
      model: openai/NousResearch/Hermes-3-Llama-3.1-8B
      api_base: http://vllm-0:8000/v1
      api_key: none
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
general_settings:
  master_key: 'sk-blacklight-key'
