version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    env_file:
      - .env
    restart: always
    networks:
      - daimon_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A worker.app worker --loglevel=debug
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://${RMQ_USER}:${RMQ_PASSWORD}@rabbitmq:5672/
    restart: always
    env_file:
      - .env
    networks:
      - daimon_network

  node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    command: python node.py
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    restart: always
    env_file:
      - .env
    networks:
      - daimon_network

volumes:
  rabbitmq_data:

networks:
  daimon_network:
    driver: bridge
