model_list:
- model_name: gpt-4o-mini
  litellm_params:
    model: openai/gpt-4o-mini
    api_key: os.environ/OPENAI_API_KEY
- model_name: hermes3
  litellm_params:
    model: ollama/hermes3
    api_base: http://localhost:11434
