name: Install and launch node
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  launch-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: cp .env.example .env
      
      # override defaults
      - run: echo -e "\n" >> .env
      - run: echo "LOCAL_HUB=true" >> .env

      # set dummy user
      - run: echo "PRIVATE_KEY=138f0cf400f34e8c8ac821c7a86bca98186b880dc0b48f2c55de47bc7f121d56" >> .env
      - run: echo "HUB_USERNAME=cicd_dummy" >> .env
      - run: echo "HUB_PASSWORD=cicd_dummy" >> .env

      - run: bash launch.sh