name: Install and launch node
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: cp .env.example .env
      
      # override defaults
      - run: echo -e "\n" >> .env
      - run: echo "OLLAMA_MODELS=" >> .env
      - run: echo "VLLM_MODELS=" >> .env

      - run: bash launch.sh