name: Build Node Container

on:
  push:
    paths:
      - 'Dockerfile*'
      - '!node/**'
      - '.github/**'
      - 'docker-compose*'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Node Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-node
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            napthaai/node:latest
            napthaai/node:${{ github.sha }}
      
      - name: Build Node Dev Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-node-dev
          push: false
          platforms: linux/amd64,linux/arm64,darwin/arm64
          tags: |
            napthaai/node-dev:latest
            napthaai/node-dev:${{ github.sha }}