name: Deploy Application

on:
  push:
    branches:
      - feat/deploy-actions # TODO: Change to main later
  pull_request:
    types:
      - closed
    branches:
      - feat/deploy-actions # TODO: Change to main later

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to A100 Instance
        env:
          HOST: ${{ secrets.A100_HOST_2 }}
          DEPLOY_USER: ${{ secrets.A100_USER }}
          DEPLOY_PATH: ${{ secrets.A100_DEPLOY_PATH }}
        run: |
          # Pass environment variables explicitly to the SSH command
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$HOST "DEPLOY_PATH='${DEPLOY_PATH}' bash -s" << 'EOF'
            echo "Current user: $(whoami)"
            echo "Current directory: $(pwd)"
            echo "DEPLOY_PATH: ${DEPLOY_PATH}"
            
            if [ -z "${DEPLOY_PATH}" ]; then
              echo "Error: DEPLOY_PATH is not set"
              exit 1
            fi

            # Create and navigate to deploy path
            sudo mkdir -p ${DEPLOY_PATH}
            echo "Listing DEPLOY_PATH directory:"
            ls -la ${DEPLOY_PATH}
            
            sudo chown -R $(whoami):$(whoami) ${DEPLOY_PATH}
            cd ${DEPLOY_PATH}
            echo "After cd to DEPLOY_PATH:"
            pwd
            ls -la
          EOF

      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful to A100 Instance"
          else
            echo "❌ Deployment failed for A100 Instance"
          fi