name: Test SDK

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment: development
          
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up NODE env variables
          env: 
            NAPTHA_HUB_USERNAME: ${{ vars.NAPTHA_HUB_USERNAME }}
            NAPTHA_HUB_PVT_KEY: ${{ secrets.NAPTHA_HUB_PVT_KEY }}
            NAPTHA_HUB_PASSWORD: ${{ secrets.NAPTHA_HUB_PASSWORD }}
          run: |
            cp .env.example .env
        
            # override defaults
            echo -e "\n" >> .env
            echo "LOCAL_HUB=true" >> .env
            
            # avoid downloading large models
            echo "OLLAMA_MODELS=" >> .env
            echo "VLLM_MODELS=" >> .env
            echo "OPENAI_MODELS=" >> .env
            
            # set dummy user
            echo "${NAPTHA_HUB_PVT_KEY}" > "${NAPTHA_HUB_USERNAME}.pem"
            echo "PRIVATE_KEY=${NAPTHA_HUB_USERNAME}.pem" >> .env
            echo "HUB_USERNAME=${NAPTHA_HUB_USERNAME}" >> .env
            echo "HUB_PASSWORD=${NAPTHA_HUB_PASSWORD}" >> .env

        - name: Install node
          run: bash launch.sh
        
        - name: Install Poetry for SDK
          uses: snok/install-poetry@v1





        - name: Install SDK dependencies
          run: |
            ls -l

        - name: Checkout SDK repo
          uses: actions/checkout@v4
          with:
            repository: NapthaAI/naptha-sdk
            fetch-depth: 1
        
        
            

        # - name: Install SDK dependencies
        #   run: |
        #     poetry lock
        #     poetry install
        
        # - name: Set up SDK env variables
        #   env: 
        #     NAPTHA_HUB_USERNAME: ${{ vars.NAPTHA_HUB_USERNAME }}
        #     NAPTHA_HUB_PVT_KEY: ${{ secrets.NAPTHA_HUB_PVT_KEY }}
        #     NAPTHA_HUB_PASSWORD: ${{ secrets.NAPTHA_HUB_PASSWORD }}
        #   run: |
        #     cp .env.example .env
        
        #     # override defaults
        #     echo -e "\n" >> .env
        #     echo "LOCAL_HUB=true" >> .env
        #     echo "HUB_URL=ws://localhost:3001/rpc" >> .env
        #     echo "NODE_URL=http://localhost:7001" >> .env
            
        #     # set dummy user
        #     echo "${NAPTHA_HUB_PVT_KEY}" > "${NAPTHA_HUB_USERNAME}.pem"
        #     echo "PRIVATE_KEY=${NAPTHA_HUB_USERNAME}.pem" >> .env
        #     echo "HUB_USERNAME=${NAPTHA_HUB_USERNAME}" >> .env
        #     echo "HUB_PASSWORD=${NAPTHA_HUB_PASSWORD}" >> .env
        
        # - name: Install SDK dependencies
        #   run: |
        #     pytest -v tests/test_cli.py